version: "3.9"

services:
  web:
    build: .
    container_name: rails_web
    ports:
      - "9000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/finances
      - RAILS_ENV=development
      - BUNDLE_PATH=/bundle
    volumes:
      - .:/app
      - bundle_cache:/bundle
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: rails_db
    ports:
      - "9002:5432"
    environment:
      - POSTGRES_DB=finances
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  bundle_cache:
